// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: HU7

#ifndef UI_MAPSCREEN_H
#define UI_MAPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MapScreen
extern void ui_MapScreen_screen_init(void);
extern void ui_MapScreen_screen_destroy(void);
extern lv_obj_t * ui_MapScreen;
extern lv_obj_t * ui_ContentMap;
extern lv_obj_t * ui_ImgDummyMap;
extern lv_obj_t * ui_UnderBarMap;
extern void ui_event_BackBtn2(lv_event_t * e);
extern lv_obj_t * ui_BackBtn2;
extern lv_obj_t * ui_MenuBtn2;
extern lv_obj_t * ui_CurrentMedia2;
extern void ui_event_HomeBtn2(lv_event_t * e);
extern lv_obj_t * ui_HomeBtn2;
extern lv_obj_t * ui_CurrentMediaTxt2;
extern lv_obj_t * ui_ETA;
extern lv_obj_t * ui_LeftDist;
extern lv_obj_t * ui_Dst;
extern lv_obj_t * ui_TopBarMap;
extern lv_obj_t * ui_CurTime;
extern lv_obj_t * ui_CurSpeed;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

