// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: HU7

#include "ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_TopBar = NULL;
lv_obj_t * ui_Time = NULL;
lv_obj_t * ui_Mode = NULL;
lv_obj_t * ui_Date = NULL;
lv_obj_t * ui_UnderBar = NULL;
lv_obj_t * ui_BackBtn = NULL;
lv_obj_t * ui_MenuBtn = NULL;
lv_obj_t * ui_CurrentMedia = NULL;
lv_obj_t * ui_HomeBtn = NULL;
lv_obj_t * ui_CurrentMediaTxt = NULL;
lv_obj_t * ui_ContentHome = NULL;
lv_obj_t * ui_ContSet = NULL;
lv_obj_t * ui_CardSet = NULL;
lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_ContCon = NULL;
lv_obj_t * ui_CardCon = NULL;
lv_obj_t * ui_Connect = NULL;
lv_obj_t * ui_ContMap = NULL;
lv_obj_t * ui_CardMap = NULL;
lv_obj_t * ui_Map = NULL;
lv_obj_t * ui_ContMedia = NULL;
lv_obj_t * ui_CardMedia = NULL;
lv_obj_t * ui_Media = NULL;
// event funtions
void ui_event_MenuBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setting, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Setting_screen_init);
    }
}

void ui_event_HomeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContentHome, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_CardSet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setting, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Setting_screen_init);
    }
}

void ui_event_CardCon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContentHome, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_CardMap(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MapScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MapScreen_screen_init);
    }
}

void ui_event_CardMedia(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContentHome, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_TopBar);
    lv_obj_set_height(ui_TopBar, 80);
    lv_obj_set_width(ui_TopBar, lv_pct(100));
    lv_obj_set_x(ui_TopBar, -1);
    lv_obj_set_y(ui_TopBar, lv_pct(-44));
    lv_obj_set_align(ui_TopBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBar, lv_color_hex(0x30323F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_TopBar);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 449);
    lv_obj_set_y(ui_Time, 0);
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "00:00");

    ui_Mode = lv_label_create(ui_TopBar);
    lv_obj_set_width(ui_Mode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mode, -431);
    lv_obj_set_y(ui_Mode, 0);
    lv_obj_set_align(ui_Mode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mode, "Home");

    ui_Date = lv_label_create(ui_TopBar);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, -12);
    lv_obj_set_y(ui_Date, 0);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "2026.06.01");

    ui_UnderBar = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_UnderBar);
    lv_obj_set_height(ui_UnderBar, 80);
    lv_obj_set_width(ui_UnderBar, lv_pct(100));
    lv_obj_set_x(ui_UnderBar, 0);
    lv_obj_set_y(ui_UnderBar, lv_pct(44));
    lv_obj_set_align(ui_UnderBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_UnderBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UnderBar, lv_color_hex(0x30323F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UnderBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackBtn = lv_btn_create(ui_UnderBar);
    lv_obj_set_width(ui_BackBtn, 52);
    lv_obj_set_height(ui_BackBtn, 50);
    lv_obj_set_x(ui_BackBtn, -465);
    lv_obj_set_y(ui_BackBtn, 0);
    lv_obj_set_align(ui_BackBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuBtn = lv_btn_create(ui_UnderBar);
    lv_obj_set_width(ui_MenuBtn, 52);
    lv_obj_set_height(ui_MenuBtn, 50);
    lv_obj_set_x(ui_MenuBtn, -336);
    lv_obj_set_y(ui_MenuBtn, 0);
    lv_obj_set_align(ui_MenuBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MenuBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentMedia = lv_img_create(ui_UnderBar);
    lv_obj_set_width(ui_CurrentMedia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentMedia, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentMedia, 256);
    lv_obj_set_y(ui_CurrentMedia, 0);
    lv_obj_set_align(ui_CurrentMedia, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CurrentMedia, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CurrentMedia, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeBtn = lv_btn_create(ui_UnderBar);
    lv_obj_set_width(ui_HomeBtn, 52);
    lv_obj_set_height(ui_HomeBtn, 50);
    lv_obj_set_x(ui_HomeBtn, -401);
    lv_obj_set_y(ui_HomeBtn, 0);
    lv_obj_set_align(ui_HomeBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentMediaTxt = lv_label_create(ui_UnderBar);
    lv_obj_set_width(ui_CurrentMediaTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentMediaTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentMediaTxt, 355);
    lv_obj_set_y(ui_CurrentMediaTxt, 0);
    lv_obj_set_align(ui_CurrentMediaTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentMediaTxt, "No Media");

    ui_ContentHome = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_ContentHome);
    lv_obj_set_height(ui_ContentHome, 441);
    lv_obj_set_width(ui_ContentHome, lv_pct(100));
    lv_obj_set_align(ui_ContentHome, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContentHome, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContSet = lv_obj_create(ui_ContentHome);
    lv_obj_remove_style_all(ui_ContSet);
    lv_obj_set_height(ui_ContSet, 372);
    lv_obj_set_width(ui_ContSet, lv_pct(21));
    lv_obj_set_y(ui_ContSet, 0);
    lv_obj_set_x(ui_ContSet, lv_pct(37));
    lv_obj_set_align(ui_ContSet, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContSet, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CardSet = lv_btn_create(ui_ContSet);
    lv_obj_set_height(ui_CardSet, 372);
    lv_obj_set_width(ui_CardSet, lv_pct(100));
    lv_obj_set_align(ui_CardSet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CardSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CardSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Settings = lv_label_create(ui_ContSet);
    lv_obj_set_width(ui_Settings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings, 0);
    lv_obj_set_y(ui_Settings, -153);
    lv_obj_set_align(ui_Settings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings, "Settings");

    ui_ContCon = lv_obj_create(ui_ContentHome);
    lv_obj_remove_style_all(ui_ContCon);
    lv_obj_set_height(ui_ContCon, 372);
    lv_obj_set_width(ui_ContCon, lv_pct(21));
    lv_obj_set_y(ui_ContCon, 0);
    lv_obj_set_x(ui_ContCon, lv_pct(12));
    lv_obj_set_align(ui_ContCon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContCon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CardCon = lv_btn_create(ui_ContCon);
    lv_obj_set_height(ui_CardCon, 372);
    lv_obj_set_width(ui_CardCon, lv_pct(100));
    lv_obj_set_align(ui_CardCon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CardCon, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CardCon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Connect = lv_label_create(ui_ContCon);
    lv_obj_set_width(ui_Connect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Connect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Connect, 0);
    lv_obj_set_y(ui_Connect, -141);
    lv_obj_set_align(ui_Connect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Connect, "Connect");

    ui_ContMap = lv_obj_create(ui_ContentHome);
    lv_obj_remove_style_all(ui_ContMap);
    lv_obj_set_height(ui_ContMap, 372);
    lv_obj_set_width(ui_ContMap, lv_pct(21));
    lv_obj_set_y(ui_ContMap, 0);
    lv_obj_set_x(ui_ContMap, lv_pct(-13));
    lv_obj_set_align(ui_ContMap, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContMap, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CardMap = lv_btn_create(ui_ContMap);
    lv_obj_set_height(ui_CardMap, 372);
    lv_obj_set_width(ui_CardMap, lv_pct(100));
    lv_obj_set_align(ui_CardMap, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CardMap, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CardMap, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Map = lv_label_create(ui_ContMap);
    lv_obj_set_width(ui_Map, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Map, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Map, 0);
    lv_obj_set_y(ui_Map, -143);
    lv_obj_set_align(ui_Map, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Map, "Map");

    ui_ContMedia = lv_obj_create(ui_ContentHome);
    lv_obj_remove_style_all(ui_ContMedia);
    lv_obj_set_height(ui_ContMedia, 372);
    lv_obj_set_width(ui_ContMedia, lv_pct(21));
    lv_obj_set_y(ui_ContMedia, 0);
    lv_obj_set_x(ui_ContMedia, lv_pct(-38));
    lv_obj_set_align(ui_ContMedia, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContMedia, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CardMedia = lv_btn_create(ui_ContMedia);
    lv_obj_set_height(ui_CardMedia, 372);
    lv_obj_set_width(ui_CardMedia, lv_pct(100));
    lv_obj_set_align(ui_CardMedia, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CardMedia, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CardMedia, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Media = lv_label_create(ui_ContMedia);
    lv_obj_set_width(ui_Media, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Media, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Media, 0);
    lv_obj_set_y(ui_Media, -144);
    lv_obj_set_align(ui_Media, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Media, "Media");

    lv_obj_add_event_cb(ui_MenuBtn, ui_event_MenuBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeBtn, ui_event_HomeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CardSet, ui_event_CardSet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CardCon, ui_event_CardCon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CardMap, ui_event_CardMap, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CardMedia, ui_event_CardMedia, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_TopBar = NULL;
    ui_Time = NULL;
    ui_Mode = NULL;
    ui_Date = NULL;
    ui_UnderBar = NULL;
    ui_BackBtn = NULL;
    ui_MenuBtn = NULL;
    ui_CurrentMedia = NULL;
    ui_HomeBtn = NULL;
    ui_CurrentMediaTxt = NULL;
    ui_ContentHome = NULL;
    ui_ContSet = NULL;
    ui_CardSet = NULL;
    ui_Settings = NULL;
    ui_ContCon = NULL;
    ui_CardCon = NULL;
    ui_Connect = NULL;
    ui_ContMap = NULL;
    ui_CardMap = NULL;
    ui_Map = NULL;
    ui_ContMedia = NULL;
    ui_CardMedia = NULL;
    ui_Media = NULL;

}
