// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: HU7

#include "ui.h"

lv_obj_t * ui_Setting1 = NULL;
lv_obj_t * ui_TopBar2 = NULL;
lv_obj_t * ui_Time2 = NULL;
lv_obj_t * ui_Mode2 = NULL;
lv_obj_t * ui_Date2 = NULL;
lv_obj_t * ui_UnderBar2 = NULL;
lv_obj_t * ui_BackBtn3 = NULL;
lv_obj_t * ui_CurrentMedia3 = NULL;
lv_obj_t * ui_HomeBtn3 = NULL;
lv_obj_t * ui_CurrentMediaTxt3 = NULL;
lv_obj_t * ui_ContentSetInfo = NULL;
lv_obj_t * ui_PanelInfo = NULL;
lv_obj_t * ui_TextVersion1 = NULL;
lv_obj_t * ui_TextDrvTemp1 = NULL;
lv_obj_t * ui_TextPsgTemp1 = NULL;
lv_obj_t * ui_TextFanSpd1 = NULL;
lv_obj_t * ui_TextMode1 = NULL;
lv_obj_t * ui_TxtCurVer1 = NULL;
lv_obj_t * ui_TxtCurDrvTmp1 = NULL;
lv_obj_t * ui_TxtCurPsgTmp2 = NULL;
lv_obj_t * ui_TxtCurPsgTmp3 = NULL;
lv_obj_t * ui_TextCurMode1 = NULL;
// event funtions
void ui_event_Setting1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
    }
}

void ui_event_BackBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setting, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Setting_screen_init);
    }
}

void ui_event_HomeBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_Setting1_screen_init(void)
{
    ui_Setting1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setting1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopBar2 = lv_obj_create(ui_Setting1);
    lv_obj_remove_style_all(ui_TopBar2);
    lv_obj_set_height(ui_TopBar2, 80);
    lv_obj_set_width(ui_TopBar2, lv_pct(100));
    lv_obj_set_x(ui_TopBar2, -1);
    lv_obj_set_y(ui_TopBar2, lv_pct(-44));
    lv_obj_set_align(ui_TopBar2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopBar2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBar2, lv_color_hex(0x30323F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time2 = lv_label_create(ui_TopBar2);
    lv_obj_set_width(ui_Time2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time2, 449);
    lv_obj_set_y(ui_Time2, 0);
    lv_obj_set_align(ui_Time2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time2, "00:00");

    ui_Mode2 = lv_label_create(ui_TopBar2);
    lv_obj_set_width(ui_Mode2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mode2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mode2, -431);
    lv_obj_set_y(ui_Mode2, 0);
    lv_obj_set_align(ui_Mode2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mode2, "Home");

    ui_Date2 = lv_label_create(ui_TopBar2);
    lv_obj_set_width(ui_Date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date2, -12);
    lv_obj_set_y(ui_Date2, 0);
    lv_obj_set_align(ui_Date2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date2, "2026.06.01");

    ui_UnderBar2 = lv_obj_create(ui_Setting1);
    lv_obj_remove_style_all(ui_UnderBar2);
    lv_obj_set_height(ui_UnderBar2, 80);
    lv_obj_set_width(ui_UnderBar2, lv_pct(100));
    lv_obj_set_x(ui_UnderBar2, 0);
    lv_obj_set_y(ui_UnderBar2, lv_pct(44));
    lv_obj_set_align(ui_UnderBar2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_UnderBar2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UnderBar2, lv_color_hex(0x30323F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UnderBar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackBtn3 = lv_btn_create(ui_UnderBar2);
    lv_obj_set_width(ui_BackBtn3, 52);
    lv_obj_set_height(ui_BackBtn3, 50);
    lv_obj_set_x(ui_BackBtn3, -465);
    lv_obj_set_y(ui_BackBtn3, 0);
    lv_obj_set_align(ui_BackBtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentMedia3 = lv_img_create(ui_UnderBar2);
    lv_obj_set_width(ui_CurrentMedia3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentMedia3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentMedia3, 256);
    lv_obj_set_y(ui_CurrentMedia3, 0);
    lv_obj_set_align(ui_CurrentMedia3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CurrentMedia3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CurrentMedia3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeBtn3 = lv_btn_create(ui_UnderBar2);
    lv_obj_set_width(ui_HomeBtn3, 52);
    lv_obj_set_height(ui_HomeBtn3, 50);
    lv_obj_set_x(ui_HomeBtn3, -401);
    lv_obj_set_y(ui_HomeBtn3, 0);
    lv_obj_set_align(ui_HomeBtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentMediaTxt3 = lv_label_create(ui_UnderBar2);
    lv_obj_set_width(ui_CurrentMediaTxt3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentMediaTxt3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentMediaTxt3, 355);
    lv_obj_set_y(ui_CurrentMediaTxt3, 0);
    lv_obj_set_align(ui_CurrentMediaTxt3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentMediaTxt3, "No Media");

    ui_ContentSetInfo = lv_obj_create(ui_Setting1);
    lv_obj_remove_style_all(ui_ContentSetInfo);
    lv_obj_set_height(ui_ContentSetInfo, 441);
    lv_obj_set_width(ui_ContentSetInfo, lv_pct(100));
    lv_obj_set_align(ui_ContentSetInfo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContentSetInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelInfo = lv_obj_create(ui_ContentSetInfo);
    lv_obj_set_width(ui_PanelInfo, lv_pct(90));
    lv_obj_set_height(ui_PanelInfo, lv_pct(80));
    lv_obj_set_align(ui_PanelInfo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextVersion1 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_TextVersion1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextVersion1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextVersion1, -408);
    lv_obj_set_y(ui_TextVersion1, -150);
    lv_obj_set_align(ui_TextVersion1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextVersion1, "Version");

    ui_TextDrvTemp1 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_TextDrvTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextDrvTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextDrvTemp1, -408);
    lv_obj_set_y(ui_TextDrvTemp1, -120);
    lv_obj_set_align(ui_TextDrvTemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextDrvTemp1, "DrvTemp");

    ui_TextPsgTemp1 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_TextPsgTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextPsgTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextPsgTemp1, -408);
    lv_obj_set_y(ui_TextPsgTemp1, -90);
    lv_obj_set_align(ui_TextPsgTemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextPsgTemp1, "PsgTemp");

    ui_TextFanSpd1 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_TextFanSpd1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextFanSpd1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextFanSpd1, -408);
    lv_obj_set_y(ui_TextFanSpd1, -60);
    lv_obj_set_align(ui_TextFanSpd1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextFanSpd1, "FanSpeed");

    ui_TextMode1 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_TextMode1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextMode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextMode1, -408);
    lv_obj_set_y(ui_TextMode1, -30);
    lv_obj_set_align(ui_TextMode1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextMode1, "Mode");

    ui_TxtCurVer1 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_TxtCurVer1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TxtCurVer1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtCurVer1, -300);
    lv_obj_set_y(ui_TxtCurVer1, -150);
    lv_obj_set_align(ui_TxtCurVer1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TxtCurVer1, "0.3");

    ui_TxtCurDrvTmp1 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_TxtCurDrvTmp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TxtCurDrvTmp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtCurDrvTmp1, -300);
    lv_obj_set_y(ui_TxtCurDrvTmp1, -120);
    lv_obj_set_align(ui_TxtCurDrvTmp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TxtCurDrvTmp1, "24");

    ui_TxtCurPsgTmp2 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_TxtCurPsgTmp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TxtCurPsgTmp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtCurPsgTmp2, -300);
    lv_obj_set_y(ui_TxtCurPsgTmp2, -90);
    lv_obj_set_align(ui_TxtCurPsgTmp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TxtCurPsgTmp2, "24");

    ui_TxtCurPsgTmp3 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_TxtCurPsgTmp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TxtCurPsgTmp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtCurPsgTmp3, -300);
    lv_obj_set_y(ui_TxtCurPsgTmp3, -60);
    lv_obj_set_align(ui_TxtCurPsgTmp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TxtCurPsgTmp3, "0");

    ui_TextCurMode1 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_TextCurMode1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextCurMode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextCurMode1, -300);
    lv_obj_set_y(ui_TextCurMode1, -30);
    lv_obj_set_align(ui_TextCurMode1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextCurMode1, "Face");

    lv_obj_add_event_cb(ui_BackBtn3, ui_event_BackBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeBtn3, ui_event_HomeBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting1, ui_event_Setting1, LV_EVENT_ALL, NULL);

}

void ui_Setting1_screen_destroy(void)
{
    if(ui_Setting1) lv_obj_del(ui_Setting1);

    // NULL screen variables
    ui_Setting1 = NULL;
    ui_TopBar2 = NULL;
    ui_Time2 = NULL;
    ui_Mode2 = NULL;
    ui_Date2 = NULL;
    ui_UnderBar2 = NULL;
    ui_BackBtn3 = NULL;
    ui_CurrentMedia3 = NULL;
    ui_HomeBtn3 = NULL;
    ui_CurrentMediaTxt3 = NULL;
    ui_ContentSetInfo = NULL;
    ui_PanelInfo = NULL;
    ui_TextVersion1 = NULL;
    ui_TextDrvTemp1 = NULL;
    ui_TextPsgTemp1 = NULL;
    ui_TextFanSpd1 = NULL;
    ui_TextMode1 = NULL;
    ui_TxtCurVer1 = NULL;
    ui_TxtCurDrvTmp1 = NULL;
    ui_TxtCurPsgTmp2 = NULL;
    ui_TxtCurPsgTmp3 = NULL;
    ui_TextCurMode1 = NULL;

}
