// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: HU7

#ifndef UI_SETTING_H
#define UI_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Setting
extern void ui_Setting_screen_init(void);
extern void ui_Setting_screen_destroy(void);
extern void ui_event_Setting(lv_event_t * e);
extern lv_obj_t * ui_Setting;
extern lv_obj_t * ui_TopBar1;
extern lv_obj_t * ui_Time1;
extern lv_obj_t * ui_Mode1;
extern lv_obj_t * ui_Date1;
extern lv_obj_t * ui_UnderBar1;
extern void ui_event_BackBtn1(lv_event_t * e);
extern lv_obj_t * ui_BackBtn1;
extern lv_obj_t * ui_CurrentMedia1;
extern void ui_event_HomeBtn1(lv_event_t * e);
extern lv_obj_t * ui_HomeBtn1;
extern lv_obj_t * ui_CurrentMediaTxt1;
extern lv_obj_t * ui_ContentSet;
extern lv_obj_t * ui_ContentInfo;
extern void ui_event_CardInfo(lv_event_t * e);
extern lv_obj_t * ui_CardInfo;
extern lv_obj_t * ui_TextInfo;
extern lv_obj_t * ui_ContentWifi;
extern lv_obj_t * ui_CardWifi;
extern lv_obj_t * ui_TextWifi;
extern lv_obj_t * ui_ContentProfile;
extern lv_obj_t * ui_CardProfile;
extern lv_obj_t * ui_TextProfile;
extern lv_obj_t * ui_ContenBtnCst;
extern lv_obj_t * ui_CardBtnCst;
extern lv_obj_t * ui_TextCstBtn;
extern lv_obj_t * ui_ContentConnect;
extern lv_obj_t * ui_CardConnect;
extern lv_obj_t * ui_TextConnect;
extern lv_obj_t * ui_ContenGeneral;
extern lv_obj_t * ui_CardGeneral;
extern lv_obj_t * ui_TextGeneral;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

