#ifndef CAN_PROTOCOL_H
#define CAN_PROTOCOL_H

#include <stdint.h>

#include "../../GDS.h"

#define CAN_ID_CONTROL_REQUEST GDS_CAN_ID_CONTROL_REQUEST
#define CAN_ID_CONTROL_RESPONSE GDS_CAN_ID_CONTROL_RESPONSE
#define CAN_ID_HVAC_STATUS GDS_CAN_ID_HVAC_STATUS
#define CAN_DLC GDS_CAN_DLC

#endif
